services:
  #seeding api
  animals-seed:
    build: ./startup
    links:
      - "animals-api:api"
    depends_on:
      animals-api:
        condition: service_healthy

  #containers
  animals-api:
    build: ./animals-api
    healthcheck:
      test: curl --fail http://localhost:5000/healthcheck || exit 1
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    links:
      - "postgres:database"
      - "rabbitmq:broker"
    ports:
      - "8000:5000"
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672